baseurl = "https://codexdelamarca.com/"
languageCode = "es"
defaultContentLanguage = "es" # en / zh-CN / ... (This field determines which i18n file to use)


theme = "codex"
paginate = 21 #gridstyle use 3 column. so should be 3,6,9,12,15....
hasCJKLanguage = false # has chinese/japanese/korean ?
[taxonomies]
  tag = "tags"
  category = "categories"
  minlevel = "minlevels"
  maxlevel = "maxlevels"
  price = "prices"
  session = "sessions"
  mincharacter = "mincharacters"
  maxcharacter = "maxcharacters"
  eval = "evals"
  author = "authors"

[related]
    threshold = 8
    includeNewer = true
    toLower = true
    [[indices]]
    name = "tags"
    weight = 100

[markup.goldmark.renderer]
unsafe= true
[languages.es]
weight = 0
languageName = "English"
contentDir = "content/es"
[languages.es.params]
      title = "Codex de la Marca"
      authorinfo = "<h5>Codex de la Marca: Angela Rivera Campos y Pablo Ruiz Múzquiz. Diseño de Juan de la Cruz</h5>"
      licenseinfo = "<p class=\"w3-small\">Codex de la Marca agredece el apoyo del <a href='https://lamarcadeleste.com'>Grupo Creativo de La Marca del Este</a>.</p>"
      logotext = "Codex de la Marca" # logo text
      isso_baseurl=""  #if you want to use isso as comment system,set your isso js baseurl here. It is like "https://isso.yourwebsite.com/" or "https://yourwebsite.com/isso/"
      isso_langcode="es"
      cookie_info = "This website uses cookies to ensure you get the best experience on our website. [Learn more](/privacy-policy/)"

[[languages.es.menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

[[languages.es.menu.main]]
    name = "Sobre el Códex"
    url = "/about/"
    weight = 15
[[languages.es.menu.main]]
    name = "Líneas"
    url = "/categories/"
    weight = 3
[[languages.es.menu.main]]
    name = "Etiquetas"
    url = "/tags/"
    weight = 4
[[languages.es.menu.main]]
    name = "Autoría"
    url = "/authors/"
    weight = 5

[[languages.es.menu.main]]
    name = "Todas"
    url = "/allposts/"
    weight = 5



[params]
    welcomemessage = false #if set true. The home page will display the content of _index.md
    authorandlicense = true
    authorimgurl = "https://raw.githubusercontent.com/jesselau76/hugo-w3-simple/master/exampleSite/images/johndoe.jpg" #if authorandlicense set true, this one must be set too

    relatedPosts = true

    backtotop = false
    lazyload = false  #if set true, lazy load images on websites asynchronously — that is, after the above-the-fold content is fully loaded, or even conditionally, only when they appear in the browser's viewport.
    glowlogo = true # if want logo to have glowing style, set true.
    scrollindicator = true # if need scroll indicator on the top, set true
    allliststyle = false  # list post with sortable all list style. If false then gridstyle or simple style
    gridstyle = true  # list post with grid style. If false then simple list
    readingtime = false  #display reading time
    firstpic = true  # display first picture as thumbnail if no thumbnail set. For gridstyle only
    socialshare = true
    socialicon = true
    googletranslate = false
    searchfunction = false #If true, it will only display search button but real search function is not included in example site because it need server-side app. To see the demo please visit https://jesselau.com
    description = "Códex de la Marca"
    onesignalid = ""  #one signal push app id
    # adsenseid="ca-pub-123456789"
    allowads = false
    logotext = "HUGO W3 SIMPLE" # logo text
    footer = "&copy; 2024 <a href=\"https://codexdelamarca.com\">Codex de la Marca</a>"


[params.social]  # Set your social account here, if you don't have some accounts just comment them
     i-github = "https://github.com/diacritica/codexlmde"
